name: provider
description: A wrapper around InheritedWidget to make them easier to use and more reusable.
version: 6.1.5+1
repository: https://github.com/rrousselGit/provider
issue_tracker: https://github.com/rrousselGit/provider/issues

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

resolution: workspace

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The version is `any` because it is defined by Flutter SDK.
  leak_tracker: any
  mockito: ^5.0.0
  test: ^1.15.5
